Repository four-four-four/DAMOA-Backend, pull requests merged in 2021-12, with the labels that each got.

#6 Feature/util/#5
  build.gradle
  src/main/java/com/fourfourfour/damoa/DamoaApplication.java
  src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImpl.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/UserDao.java
  src/main/java/com/fourfourfour/damoa/model/dto/response/BasicResponseDto.java
  src/main/java/com/fourfourfour/damoa/model/dto/user/UserDto.java
  src/main/java/com/fourfourfour/damoa/model/service/user/UserService.java
  src/main/java/com/fourfourfour/damoa/model/service/user/UserServiceImpl.java
  src/test/java/com/damoa/DamoaApplicationTests.java
  src/test/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImplTest.java
Labels: 0xe82de, feature

#8 Feature/user/#7
  build.gradle
  src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImpl.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/UserDao.java
  src/main/java/com/fourfourfour/damoa/model/dto/response/ErrorSerializer.java
  src/main/java/com/fourfourfour/damoa/model/dto/user/UserDto.java
  src/main/java/com/fourfourfour/damoa/model/service/user/UserService.java
  src/main/java/com/fourfourfour/damoa/model/service/user/UserServiceImpl.java
Labels: feature, zlzzlzz2l

#11 Feature/util/#9
  build.gradle
  src/main/java/com/fourfourfour/damoa/config/CorsConfig.java
  src/main/java/com/fourfourfour/damoa/config/SecurityConfig.java
  src/main/java/com/fourfourfour/damoa/config/auth/PrincipalDetails.java
  src/main/java/com/fourfourfour/damoa/config/auth/PrincipalDetailsService.java
  src/main/java/com/fourfourfour/damoa/config/jwt/JwtAuthorizationFilter.java
  src/main/java/com/fourfourfour/damoa/config/jwt/JwtProperties.java
  src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/JdbcUserDaoImpl.java
  src/main/java/com/fourfourfour/damoa/model/dao/user/UserDao.java
  src/main/java/com/fourfourfour/damoa/model/dto/user/UserDto.java
Labels: 0xe82de, feature

#14 Refactor/util/#13
  src/main/java/com/fourfourfour/damoa/config/CorsConfig.java
  src/main/java/com/fourfourfour/damoa/controller/user/UserController.java
Labels: 0xe82de, refactor
