Repository four-four-four/DAMOA-Backend, pull requests merged in 2022-03, with the labels that each got.

#29 [공통] 백엔드 배포 스크립트 추가
  scripts/backend-deploy.sh
Labels: 0xe82de, common

#30 Fix: #28 - 백엔드 배포 스크립트 수정
  scripts/backend-deploy.sh
Labels: bug, 0xe82de

#33 Feature/common/#31
  .gitignore
  src/main/java/com/fourfourfour/damoa/api/member/controller/MemberController.java
  src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqLoginMemberDto.java
  src/main/java/com/fourfourfour/damoa/api/member/dto/req/ReqRegisterMemberDto.java
  src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepository.java
  src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepositoryCustom.java
  src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepositoryImpl.java
  src/main/java/com/fourfourfour/damoa/api/member/service/MemberService.java
  src/main/java/com/fourfourfour/damoa/api/member/service/MemberServiceImpl.java
  src/main/java/com/fourfourfour/damoa/common/auth/JwtAuthenticationFilter.java
  src/main/java/com/fourfourfour/damoa/common/auth/PrincipalDetailsService.java
  src/main/java/com/fourfourfour/damoa/common/dto/response/BaseResponseDto.java
  src/main/java/com/fourfourfour/damoa/common/entity/BaseCreatedEntity.java
  src/main/java/com/fourfourfour/damoa/common/entity/BaseLastModifiedEntity.java
  src/main/java/com/fourfourfour/damoa/common/exception/handler/GlobalControllerAdvice.java
  src/main/java/com/fourfourfour/damoa/common/interceptor/LogInterceptor.java
  src/main/java/com/fourfourfour/damoa/common/message/ErrorMessage.java
  src/main/java/com/fourfourfour/damoa/common/message/Message.java
  src/main/java/com/fourfourfour/damoa/common/util/JwtTokenUtil.java
  src/main/java/com/fourfourfour/damoa/common/util/LogUtil.java
  src/main/java/com/fourfourfour/damoa/common/util/ResponseBodyWriteUtil.java
  src/main/java/com/fourfourfour/damoa/config/security/CorsConfig.java
  src/main/java/com/fourfourfour/damoa/config/security/SecurityConfig.java
  src/main/java/com/fourfourfour/damoa/config/web/WebConfig.java
  src/main/resources/application.yml
  src/main/resources/errors.properties
  src/main/resources/messages.properties
Labels: 0xe82de, refactor

#34 Feature/admin/#32
  src/main/java/com/fourfourfour/damoa/api/member/repository/MemberRepository.java
  src/main/java/com/fourfourfour/damoa/api/notice/controller/NoticeController.java
  src/main/java/com/fourfourfour/damoa/api/notice/dto/req/ReqNoticeDto.java
  src/main/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepository.java
  src/main/java/com/fourfourfour/damoa/api/notice/service/NoticeService.java
  src/main/java/com/fourfourfour/damoa/api/notice/service/NoticeServiceImpl.java
  src/main/java/com/fourfourfour/damoa/common/message/ErrorMessage.java
  src/main/java/com/fourfourfour/damoa/common/message/Message.java
  src/main/resources/errors.properties
  src/main/resources/messages.properties
  src/test/java/com/fourfourfour/damoa/api/notice/repository/NoticeRepositoryTest.java
  src/test/java/com/fourfourfour/damoa/api/notice/service/NoticeServiceImplTest.java
Labels: feature, zlzzlzz2l
